### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by nevitdilmen** [dreampowder/Osirix-ColorMRI#10]
Plugin crashes when executed on the following patient from another imaging center.  
Color MRI  Plugin Version 0.4 
[Colorbug_19821221.zip](https://github.com/dreampowder/Osirix-ColorMRI/files/1923347/Colorbug_19821221.zip)

**Comment by dreampowder** [comment]
Fixed the issue. The problem was the same with the issue #11. 
One of the images had different resolution than others. 
Updated grouping algorithm as it did gave a false flag that a set is belong to a group with image sets like this.
