### ISSUE TITLE
Crashes or create unusable series. v 0.4

### ISSUE THREAD

**Issue by nevitdilmen** [dreampowder/Osirix-ColorMRI#11]
Crashes or create unusable series. v 0.4
[Orbita Mr.zip](https://github.com/dreampowder/Osirix-ColorMRI/files/1957717/Orbita.Mr.zip)

**Comment by dreampowder** [comment]
Fixed the issue by updating the rgb image generation mechanism. On the following example scan, one of tha image sets seems to have a corrupted pixel or data. From now on the plugin will use the grayscale value as default if there is a corrupted pixel.

**Comment by dreampowder** [comment]
A Further analysis shown that one of the image sets had a smaller resolution. 
2 Images Were 256x256 and one was 240x240(s2TW_SE)
