### ISSUE TITLE
Does not use the selected series 

### ISSUE THREAD

**Issue by nevitdilmen** [dreampowder/Osirix-ColorMRI#2]
Does not use the selected series. 

![screen shot 2018-01-20 at 12 43 5a8](https://user-images.githubusercontent.com/26278991/35192879-1dd5be9c-feab-11e7-8ae2-5f130f40e7f4.png)

![screen shot 2018-01-19 at 17 50 10](https://user-images.githubusercontent.com/26278991/35192841-85dc7ce8-feaa-11e7-914b-cbe8602391ad.png)

**Comment by dreampowder** [comment]
Improved the grouping algorithm, fixed in the version 0.4
