### ISSUE TITLE
Grouping (Image planes)

### ISSUE THREAD

**Issue by nevitdilmen** [dreampowder/Osirix-ColorMRI#3]
Only images from same field of view should appear in same group. 

Here an image from Coronal series appears alongside images from sagittal series in group1. 

![screen shot 2018-01-20 at 12 43 5aa8](https://user-images.githubusercontent.com/26278991/35192943-44f4cd5a-feac-11e7-9af2-fe56fbd6b141.png)

**Comment by dreampowder** [comment]
Fixed in the latest version 0.4
