### ISSUE TITLE
Applying ColorMRI filter alters window settings of one of the series.

### ISSUE THREAD

**Issue by nevitdilmen** [dreampowder/Osirix-ColorMRI#5]
Applying ColorMRI filter alters (brightens) window settings of one of the series. (Usually first series or T1)

Image shows Jpg's exported before and after using ColorMRI filter. (T1,T2 and STIR series respectively) 

![2018-02-05_161317](https://user-images.githubusercontent.com/26278991/35806329-345847e8-0a90-11e8-8067-255a93d81bc3.jpg)

**Comment by dreampowder** [comment]
Updated the code so the new window will be focused before applying the full dynamic color filter. 
I guess this issue is closed but will leave open until further testing

**Comment by nevitdilmen** [comment]
I tested this issue with new 0.6 version. 
[Pelvik Mr.zip](https://github.com/dreampowder/Osirix-ColorMRI/files/2039762/Pelvik.Mr.zip)

Screenshot : 
![2018-05-25_173956a](https://user-images.githubusercontent.com/26278991/40550597-3f54048a-6043-11e8-8fcc-d72cf4723f4b.jpg)
