### ISSUE TITLE
Group order in plugin window

### ISSUE THREAD

**Issue by nevitdilmen** [dreampowder/Osirix-ColorMRI#6]
The order which groups appear in plugin window is not the same as group numbering. 
![screen shot 2018-02-07 at 16 57 57a](https://user-images.githubusercontent.com/26278991/35920481-08f4534a-0c29-11e8-802d-e9887bbd3c0d.png)
![screen shot 2018-02-07 at 16a 57 19](https://user-images.githubusercontent.com/26278991/35920482-091d5484-0c29-11e8-9385-6cbf99345678.png)

**Comment by dreampowder** [comment]
Fixed in v0.4
